### ISSUE TITLE
How to get a websocket connection handshake status code?

### ISSUE THREAD

**Issue by selecky** [dvmatyun/web_socket#11]
Hi @dvmatyun ,

When connecting to a websocket, I would like to intercept the handshake status code (e.g., 101 WebSocket Protocol Handshake, 401 Unauthorized, 500 Internal Server Error) to inform the user of the reason why the connection was unsuccessful, such as invalid credentials.

Is there a way how to get these handshake details?

Thanks.

**Comment by dvmatyun** [comment]
Hi @selecky . As far as I know the low-level dart webSocket implementation gives me only `closeCode` and `closeReason`, but they are not like status codes. You can see `PlatformWebsocketIo` implementation in my library and if you have any idea where I can get those statuses - I can add them to library. However, I think what is possible for you if you want to have some scenarios on "wrong" connection to server - you can just send this codes as first message from server and close connection from server side. And client will react to those status codes.
