### ISSUE TITLE
How to add the authentication header?

### ISSUE THREAD

**Issue by AiMAnsarie** [dvmatyun/web_socket#12]
Hi @dvmatyun ,

I'm using JWT authentication on my server so I wanted to know how to add the Authentication header to the connection and the sendMessage requrest.

Thanks

**Comment by dvmatyun** [comment]
hi @AiMAnsarie webSockets on web does not support any header solution. Best solution is to pass header in first message after connection is established, and if token is wrong - close connection by server. However for IO (mobile for example) you can pass `SocketOptionalParams` to `connect` method. But that will not work in web.
