### ISSUE TITLE
Sending ping to aws ApiGateway websockets

### ISSUE THREAD

**Issue by Pedrozena** [dvmatyun/web_socket#13]
Hi @dvmatyun .
I'm trying to use your library but I have some issues with the **ping** functionality.
I have a ws endpoint deployed in aws, that uses a query param for authorization purposes.
Using the ping functionality provided by your library results in a forbidden error by my ApiGateway.
```
{"message": "Forbidden", "connectionId":"ABAudfcuCGYAd1A=", "requestId":"ABCO7H6MCGYFxCA="}
```
The only way to achieve a proper response to a ping is within a shell with [wscat](https://github.com/websockets/wscat) + `--slash` flag:
```
➜  wscat -c "wss://....execute-api.eu-west-3.amazonaws.com/production/?authorization=<token>" --slash -P
Connected (press CTRL+C to quit)
> /ping
< Received pong (data: "")
```

Looking at the code, behind the scenes, wscat is using [ws](https://github.com/websockets/ws) [ping](https://github.com/websockets/ws/blob/019f28ff1ffddfcdc428d1de5ecd98648057a2ab/lib/sender.js#L234) method.

I tried to implement the solution you provided [here](https://github.com/dvmatyun/web_socket/issues/7) with the following strings:

```
  // /ping
  // ping
  // {"rpc":"ping"}
  // {"rpc":"/ping"}
  // ''
```

without success. How do I implement a ping similar to the one implemented by ws lib?

Thanks in advance for the support!

**Comment by Pedrozena** [comment]
I also tried 
```
  @override
  Object get pingServerMessage {
    Map<String, dynamic> dataSendMap = {
      "opcode": 0x09,
    };
    return json.encode(dataSendMap);
  }
```

without any luck

**Comment by Pedrozena** [comment]
Not a very orthodox/clean solution, but after reverse-engineering ws.ping(), I find that
```
  @override
  Object get pingServerMessage => Uint8List.fromList([137, 128, 184, 12, 101]);
```
works for my case.
I guess is the binary translation of opcode 0x09

**Comment by dvmatyun** [comment]
@Pedrozena ok, so I think first let's investigate what is causing the problem:
1) Are you connecting to the socket using URL with authorization token?
2) Is the problem only with pings? Can you exchange normal messages without problems? (For that you can set parameter `skipPingMessages` to `true` in the `SocketConnectionOptions` class)
3) Do you know how to exchange messages with your service manually? (see attached index.html in gist -> https://gist.github.com/dvmatyun/688fdd24e07093b8af66393ec0ebf50f  . Save it on your pc as index.html, open it in browser and there you can manually print the connection url and then exchange messages with server. Or you can try using other tools like `Postman`) Please, provide a screenshot of valid messages or ping/pong functionality (you can blur the token)

Normally to use this library you should now how to communicate with your service and then define the auth token for connection in `websocketConnectionUri` (see example) and define all the messages (text/byte) as you did in your second response.

**Comment by Pedrozena** [comment]
Hey @dvmatyun. I confirm I'm connected, and this problem occurs only with ping.
I.e: using `web_socket_channel` lib does the job since the ping is performed by the underlying dart.io WebSocket ping method with the dedicated opcode [ref](https://github.com/dart-lang/sdk/blob/88c9758ef131d430d8ce595c6bfb4c90574d3ddd/sdk/lib/_http/websocket_impl.dart#L690)

**Comment by dvmatyun** [comment]
@Pedrozena hm, I see, I think this is some kind of technical ping implementation for ping. What I will try to do (or you can by forking my library, if you like it):
1. Add ability to use this technical ping (However as I can see it carries no data and is not customizable)
2. Will make a comment that ping-pong in my library is optional custom thing, that you can disable.
For now as I can see the solution for you:
- Disable custom ping/pong by setting `skipPingMessages ` to `true`
- Either fork the library or wait for patch where I will use this setter: `void set pingInterval(Duration? interval)` from the dart core.
Let me know if you have any questions left
