### ISSUE TITLE
Cannot connect on android simulator

### ISSUE THREAD

**Issue by pikachupichu25** [dvmatyun/web_socket#4]
EDITTED:
I solved this problem. It is not a package issue.
I run web socket with localhost. In android simulator, I have to replace localhost with 10.0.2.2 .
Now, it works fine as expected

**Describe the bug**
I cannot connect websocket using Android simulator.
The same code works fine with iOS and MacOS.

**To Reproduce**

I run the code to initialize a websocket:
``` 
final connectionOptions = SocketConnectionOptions(
    pingIntervalMs: 3000, // send Ping message every 3000 ms
    timeoutConnectionMs: 4000, // connection fail timeout after 4000 ms
    /// see ping/pong messages in [logEventStream] stream
    skipPingMessages: true,
  );

final IMessageProcessor<String, String> textSocketProcessor = SocketSimpleTextProcessor();

socketHandler = IWebSocketHandler<String, String>.createClient(
      webSocketUrl,
      textSocketProcessor,
      connectionOptions: connectionOptions,
    );

isConnected = await socketHandler.connect();
print('websocket isConnected: $isConnected');
```

**Expected behavior**
isConnected should become true and websocket client should get a new connection.

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS 12.6

**Smartphone (please complete the following information):**
Simulator
- Device: Nexus 6 (android SDK build for arm64)
- OS: android version 9

Is there a way to debug this issue?

**Comment by dvmatyun** [comment]
Good job! :)
