### ISSUE TITLE
How to continue connected to the server in the background?

### ISSUE THREAD

**Issue by marciotisouza** [dvmatyun/web_socket#6]
I have an application that transmits the location in the background, but then the websocket connection is closed, how to keep the server online?

Flutter 3.10.5

**Comment by dvmatyun** [comment]
That is not possible, not because of this package/library, Operating System won't allow that. You can try using Foreground Service (For android) and try to achieve your goal there (maybe even launch web socket connection there. Let me know if I can help you by improving my package somehow.

**Comment by dvmatyun** [comment]
Will close the issue in few days if no more questions left.
