### ISSUE TITLE
Exception: Socket is already disposed!

### ISSUE THREAD

**Issue by shanelau** [dvmatyun/web_socket#8]
Looks like it happens when trying to reconnect.

Sentry catch error stack:

```
_Exception: Exception: Socket is already disposed!
  File "websocket_base_service_impl.dart", line 135, in WebSocketBaseService.connect
  File "websocket_handler_impl.dart", line 138, in WebSocketHandler._reconnectionAttempt
  File "<asynchronous suspension>"
  File "websocket_handler_impl.dart", line 100, in WebSocketHandler._socketStateChanged
```

**Comment by dvmatyun** [comment]
It seems that you are calling `void close()` somewhere in your code and then trying to connect / reconnect the same WebSocket object after it is closed completly. Try to comment all the appearances of calling close() method and check again. You should close WebSocket object only after they are not needed at all and you are not going to connect/reconnect. If you want to just disconnect WebSocket - use `disconnect('reason')` method.
Let me know if you have any questions left

**Comment by dvmatyun** [comment]
@shanelau let me know if you have any questions left. Otherwise, I will close this issue as resloved in a week
